@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJ1c2VydHlwZSI6IkFETUlOIiwiaWF0IjoxNjc5MTIxODk5LCJleHAiOjE2NzkxMjU0OTl9.CN91dAcQ7pIMIC9ILuSPnVtsVwqcnBxs5YlchY7RNOU
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJ1c2VydHlwZSI6IkFETUlOIiwiaWF0IjoxNjc5MDc5NTg0LCJleHAiOjE2NzkwODY3ODR9.Uuf-o6O2k7M6I9Wp-WRYqiXUXNRV1JvXXXgznXSdYG8
###
GET  http://localhost:3000/admin/
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET http://localhost:3000/admin/names
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/admin/id/2
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/admin/testing
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/admin/find?name=Faheem
Authorization: Bearer {{ACCESS_TOKEN}}
###
POST http://localhost:3000/admin/login
Content-Type: application/json

{
    "username": "testing",
    "password": "admin600"
}

###

POST http://localhost:3000/admin/sign-up
Content-Type: application/json

{
  "username": "testing",
  "password": "admin600",
  "name": "Faheem Arshad",
  "phone": "02003452321",
  "email": "o2f4@gmail.com",
  "address": "North Naz Karachi",
  "dob": "05-12-2001",
  "gender": "M"
}

###
POST http://localhost:3000/admin/refreshToken
Content-Type: application/json

{
  "refreshToken": "{{REFRESH_TOKEN}}"
}

###

DELETE http://localhost:3000/admin/testing
Authorization: Bearer {{ACCESS_TOKEN}}

###

PATCH http://localhost:3000/admin/testing
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name": "Faheem Arshad",
  "phone": "010012452321",
  "email": "oasd234@gmail.com",
  "address": "North Naz Karachi2",
  "dob": "05-12-2001",
  "gender": "M"
}

###

PATCH http://localhost:3000/admin/updatePwd
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "username": "testing",
  "oldPassword": "admin600",
  "newPassword": "admin600",
  "retypedNewPwd": "admin600"
}
###
GET http://localhost:3000/admin/testing/getImage
Authorization: Bearer {{ACCESS_TOKEN}}

###
//Do it on Postman 
POST http://localhost:3000/admin/testing/uploadImage
Authorization: Bearer {{ACCESS_TOKEN}}


