@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJ1c2VydHlwZSI6IkFETUlOIiwiaWF0IjoxNjc4ODI4ODcxLCJleHAiOjE2Nzg4Mjk3NzF9.5v4IzTgHj2LNOGg68wOdHTkBr1sPP4FQXtkdPDkFKNY
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJ1c2VydHlwZSI6IkFETUlOIiwiaWF0IjoxNjc4ODI4ODcxLCJleHAiOjE2Nzg4MzI0NzF9.5DddC3VdAM6Upg7fm-7a2JReweyOLYkjSjsPn0QeBQk
###
GET  http://localhost:3000/admin/
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET http://localhost:3000/admin/names
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/admin/id/8
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/admin/admin1000
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/admin/find?name=Zubair
Authorization: Bearer {{ACCESS_TOKEN}}
###
POST http://localhost:3000/admin/login
Content-Type: application/json

{
    "username": "testing",
    "password": "admin600"
}

###

POST http://localhost:3000/admin/sign-up
Content-Type: application/json

{
  "username": "testing",
  "password": "Testing1",
  "name": "Faheem Arshad",
  "phone": "02003452321",
  "email": "o2f4@gmail.com",
  "address": "North Naz Karachi",
  "dob": "05-12-2001",
  "gender": "M"
}

###
POST http://localhost:3000/admin/refreshToken
Content-Type: application/json

{
  "refreshToken": "{{REFRESH_TOKEN}}"
}

###

DELETE http://localhost:3000/admin/testing
Authorization: Bearer {{ACCESS_TOKEN}}

###

PATCH http://localhost:3000/admin/testing
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name": "Faheem Arshad",
  "phone": "010012452321",
  "email": "oasd234@gmail.com",
  "address": "North Naz Karachi2",
  "dob": "05-12-2001",
  "gender": "M"
}

###

PATCH http://localhost:3000/admin/updatePwd
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "username": "testing",
  "oldPassword": "hello123",
  "newPassword": "admin600",
  "retypedNewPwd": "admin600"
}