@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJ1c2VydHlwZSI6IkVNUExPWUVSIiwidXNlcklkIjoyLCJpYXQiOjE2ODAzMTU1OTksImV4cCI6MTY4MDMxOTE5OX0.MyFrgGdqkYR1rLZu-wx-2oS6EgL7q5vmXnKVEjKoJ0Q
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJ1c2VydHlwZSI6IkFETUlOIiwiaWF0IjoxNjc4OTIyNTE1LCJleHAiOjE2Nzg5MjYxMTV9.UGz6DDNNH-WtLWAlQ_nUGG7CwvSScL4vRh54vH7PJxI
###
GET  http://localhost:3000/employee/
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employee/names
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employee/id/1
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employee/unverified
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employee/verified
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employee/find?name=Saleem
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employee/saleem
Authorization: Bearer {{ACCESS_TOKEN}}
###
PATCH http://localhost:3000/employee/changeVerfication
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "username": "saleem",
    "verified": "true"
}

###
POST http://localhost:3000/employee/sign-up
Content-Type: application/json

{
    "username":"saleem", 
    "password":"saleem123", 
    "name": "Saleem Ahmed",
    "phone": "03110887898",
    "email": "saleem@hotmail.com",
    "address": "A-444 Gulshan",
    "dob": "01-15-2000",
    "gender": "M",
    "cnic_no": "4210141703963",
    "job_type":"Chef" 
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "saleem",
    "password": "saleem123"
}
###
DELETE  http://localhost:3000/employee/saleem
Authorization: Bearer {{ACCESS_TOKEN}}

###
PATCH http://localhost:3000/employee/saleem
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{ 
    "name": "Faseeh Ahmed",
    "phone": "03110887898",
    "email": "saleem@hotmail.com",
    "address": "A-444 Gulshan",
    "dob": "01-15-2000",
    "gender": "M",
    "cnic_no": "4210141703963",
    "job_type":"Chef" 
}
###
GET http://localhost:3000/employee/saleem/getCNIC
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET http://localhost:3000/employee/saleem/getImage
Authorization: Bearer {{ACCESS_TOKEN}}
