@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJ1c2VydHlwZSI6IkVNUExPWUVSIiwidXNlcklkIjoyLCJpYXQiOjE2ODAzMTU2OTIsImV4cCI6MTY4MDMxOTI5Mn0._kptFj_w3V22P0xq2L6zV01bddeMjP5S79ZALrTS5AI
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJ1c2VydHlwZSI6IkFETUlOIiwiaWF0IjoxNjc4OTIyNTE1LCJleHAiOjE2Nzg5MjYxMTV9.UGz6DDNNH-WtLWAlQ_nUGG7CwvSScL4vRh54vH7PJxI
###
GET  http://localhost:3000/employer/
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employer/names
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employer/id/4
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employer/find?name=Arshad
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/employer/user
Authorization: Bearer {{ACCESS_TOKEN}}
###
DELETE http://localhost:3000/employer/user
Authorization: Bearer {{ACCESS_TOKEN}}
###
POST http://localhost:3000/employer/
Content-Type: application/json

{
  "username": "user",
  "password": "user1234",
  "name": "Mursheed Arshad",
  "phone": "02003452321",
  "email": "o2f4@gmail.com",
  "address": "North Naz Karachi",
  "dob": "05-12-2001",
  "gender": "M"
}
###

PATCH http://localhost:3000/employer/user
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name": "Faheem Arshad",
  "phone": "010012452321",
  "email": "oasd234@gmail.com",
  "address": "North Naz Karachi2",
  "dob": "05-12-2001",
  "gender": "M"
}

###

PATCH http://localhost:3000/employer/updatePwd
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "username": "user",
  "oldPassword": "user123",
  "newPassword": "user112",
  "retypedNewPwd": "user112"
}

###

GET http://localhost:3000/employer/user/getImage 
Authorization:  Bearer {{ACCESS_TOKEN}}