@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbGVlbSIsInVzZXJ0eXBlIjoiRU1QTE9ZRUUiLCJ1c2VySWQiOjMsImlhdCI6MTY4MDMyMDUzMiwiZXhwIjoxNjgwMzI0MTMyfQ.003JyhhBy2_t4d7OYVxwcPxnpVKmzk2TJPNVjhjpemI
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJ1c2VydHlwZSI6IkFETUlOIiwiaWF0IjoxNjc4OTIyNTE1LCJleHAiOjE2Nzg5MjYxMTV9.UGz6DDNNH-WtLWAlQ_nUGG7CwvSScL4vRh54vH7PJxI
###
GET  http://localhost:3000/jobs/?job_type=Cooking
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/jobs/id/2
Authorization: Bearer {{ACCESS_TOKEN}}
###

GET  http://localhost:3000/jobs/find?title=Chef
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET  http://localhost:3000/jobs/uncompletedJobs
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/jobs/user/myJobs
Authorization: Bearer {{ACCESS_TOKEN}}
###
GET  http://localhost:3000/jobs/saleem/myAppliedJobs
Authorization: Bearer {{ACCESS_TOKEN}}
###
DELETE   http://localhost:3000/jobs/1
Authorization: Bearer {{ACCESS_TOKEN}}
###
POST http://localhost:3000/jobs/
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "username": "user",
    "title": "Maid Needed",
    "description": "We need require a maid",
    "job_type": "Cleaning",
    "salary": "5000"
}

###
POST http://localhost:3000/jobs/applyForJob
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "username": "saleem",
    "job_id" : "1"
}
###
PATCH  http://localhost:3000/jobs/3
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "title": "Maid Needed",
    "description": "We need require a maid 9-5",
    "job_type": "Cleaning",
    "salary": "10000",
    "completed": "false"
}

###
GET  http://localhost:3000/jobs/paged?page=1&limit=2
Authorization: Bearer {{ACCESS_TOKEN}}
###

